"""Soil context (diagnostic) and experimental soil-aware models."""

from .context import (
    MINERALIZATION_FLAG_THRESHOLD,
    MINERALIZATION_HIGH_THRESHOLD,
    PERCENT_FACTORS,
    SOIL_FACTORS,
    attach_soil_context,
    build_soil_context,
    mineralization_risk_from_pct,
    soil_confounder_context,
    soil_context_summary,
)
from .experimental import (
    C_M_PER_NS,
    SoilPhysicsDiagnostics,
    attach_soil_model_diagnostics,
    compare_depth_channels,
    depth_from_twt_ns,
    integrated_soil_model,
    soil_ab_summary,
    soil_aware_background_zscore,
    soil_background_factor_sweep,
    soil_context,
    soil_depth_diagnostic,
    soil_physics_diagnostics,
    soil_scale_weights,
    soil_twt_depth_grid,
)

__all__ = [
    "C_M_PER_NS",
    "MINERALIZATION_FLAG_THRESHOLD",
    "MINERALIZATION_HIGH_THRESHOLD",
    "PERCENT_FACTORS",
    "SOIL_FACTORS",
    "SoilPhysicsDiagnostics",
    "attach_soil_context",
    "attach_soil_model_diagnostics",
    "build_soil_context",
    "compare_depth_channels",
    "depth_from_twt_ns",
    "integrated_soil_model",
    "mineralization_risk_from_pct",
    "soil_ab_summary",
    "soil_aware_background_zscore",
    "soil_background_factor_sweep",
    "soil_confounder_context",
    "soil_context_summary",
    "soil_context",
    "soil_depth_diagnostic",
    "soil_physics_diagnostics",
    "soil_scale_weights",
    "soil_twt_depth_grid",
]
